### ISSUE TITLE
certification should not be run on OSP8

### ISSUE THREAD

**Issue by goneri** [redhat-cip/dci-ansible-agent#1]
Certification is broken on OSP8 (and OSP9 I think). We should skip rhcert on these versions.

**Comment by dsavineau** [comment]
What is exactly broken ? do you have some logs ?

**Comment by goneri** [comment]
http://wwww.distributed-ci.io/#!/jobs/ec8f933c-abe5-4bf9-afe4-8b98e386597d/results

**Comment by goneri** [comment]
No a bug.
