### ISSUE TITLE
Tempest deployment-specification not taken in account

### ISSUE THREAD

**Issue by Spredzy** [redhat-cip/dci-ansible-agent#10]
As a user, I've specified custom deployment configuration in the Control-Server in the RemoteCI > Data section, however those configurations are not taking in account.

The only way to specify tempest configuration is to override `tempest_extra_config`.

**Comment by Spredzy** [comment]
## Assumption

In OSP10, validate-tempest uses the file `~/tempest-deployer-input.conf` https://github.com/redhat-cip/dci-ansible-agent/blob/master/roles/OSP10/validate-tempest/templates/configure-tempest.sh.j2#L145

But this file is never generated https://github.com/redhat-cip/dci-ansible-agent/blob/master/dci-ansible-agent.yml#L223-L230 hence user-specific configuration is never applied.

**Comment by Spredzy** [comment]
@goneri Can you let me know if its a misunderstanding from my side and I am missing somtething

**Comment by goneri** [comment]
This is the structure we use the FV2:

```
{
  "tempest": {
    "default_overrides": [
      {
        "option": "vendor_name",
        "section": "volume",
        "value": "Dell"
      },
      {
        "option": "volume_services",
        "section": "volume-feature-enabled",
        "value": true
      },
      {
        "option": "use_dynamic_credentials",
        "section": "auth",
        "value": true
      },
      {
        "option": "api_v1",
        "section": "volume-feature-enabled",
        "value": true
      }
    ]
  }
}
```

We don't have an `tempest_extra_config` key there. The settings will be apply in `/etc/tempest/default-overrides.conf`. The file will later be used as the `~/tempest-deployer-input.conf` file.
