### ISSUE TITLE
dci-ansible-agent pushs corrupted file in the server

### ISSUE THREAD

**Issue by goneri** [redhat-cip/dci-ansible-agent#11]
https://www.distributed-ci.io/jobs/ae355e1e-164b-4faa-a07f-ed925426e230/files
certification.xml.gz

File size should be 5283900 (5MB), it's actually 9628858 (9.2MB). The job log does not show up any error.

**Comment by goneri** [comment]
I can get the document with dcictl:

```
dcictl job-download-file $job_id --file-id $file_id --target ~/tmp/certification.xml.gz
```

**Comment by goneri** [comment]
https://softwarefactory-project.io/r/#/c/10262/

**Comment by guillaumevincent** [comment]
5283900 is 5MB
It will be fixed in production soon
