### ISSUE TITLE
fetch_images.py throws attribute error due to outdated object reference

### ISSUE THREAD

**Issue by i-m-wisch** [redhat-cip/dci-ansible-agent#20]
When fetch_images.py is run with python2-docker-2.4+ (python2-docker-2.4.2-1.2.el7.noarch in my case), an error is returned:

AttributeError: 'DockerClient' object has no attribute 'pull' In Docker SDK for Python 2.0, this method is now on the object APIClient. See the low-level API section of the documentation for more details.

[https://github.com/redhat-cip/dci-ansible-agent/blob/master/fetch_images.py#L26](url)
To resolve, the line should be changed from:
`client = docker.from_env()`

to:
`client = docker.APIClient()`

**Comment by dsavineau** [comment]
We only support python-docker 1.10 coming from RHEL 7 on the jumpbox. The APIClient is only available with python-docker >= 2.3 so this change is not backward compatible.
