### ISSUE TITLE
Teardown is run before spawning the undercloud

### ISSUE THREAD

**Issue by fcharlier** [redhat-cip/dci-ansible-agent#3]
Teardown is run before spawning the undercloud which is a nonsense as teardown role should be to clean stuff after the agent execution.

**Comment by fcharlier** [comment]
Fix proposed for review: https://softwarefactory-project.io/r/9615

**Comment by Spredzy** [comment]
@fcharlier For debugging purposes, agent operator might decide to not teardown after job failure, so they can log in and see what went wrong with their deployment.

The teardown ran before the pre-run is here to ensure that the agent will run on vanilla platform.

Ideally, teardown hook is smart enough to do nothing if the platform is already teareddown, and move directly to pre-run.

**Comment by fcharlier** [comment]
IMHO, if `teardown_on_failure == False`, the teardown procedure should be manual. All other *initial* cleanup should be handled in the `pre-run` hook.
